# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-09 21:18
from __future__ import unicode_literals

from django.db import migrations, models
import utils.randstr


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
        migrations.AddField(
            model_name='post',
            name='uu_id',
            field=models.CharField(default=utils.randstr.generate_code, max_length=10),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='published', max_length=10),
        ),
    ]
