# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-10 13:24
from __future__ import unicode_literals

from django.db import migrations, models
import utils.randstr


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20171109_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='uu_id',
            field=models.CharField(default=utils.randstr.generate_code, max_length=8),
        ),
    ]
